name: TestingTestingAH
favicon: null
layout_spectrum: 0.973623557947576
typography_spectrum: 0.0574049677234143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20680337166413665
  lightness: 0.9156850012950599
  saturation: 0.27705074776895344
  rhythmicContrast: 0.5811808703001589
purpose: []
