name: TestingTestingAH
favicon: null
layout_spectrum: 0.94425
typography_spectrum: 0.17023
title: Test of the Grid Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.27705074776895344
  rhythmicContrast: 0.75
purpose: []
